{% set data = load_setuptools() %}

package:
  name: zipline
  version: 0.8.4

build:
  number: 0

source:
  path: ../../

requirements:
  build:
    - python
    {% for req in data.get('build_requires', []) -%}
    - {{req}}
    {% endfor %}
  run:
    - python
    {% for req in data.get('install_requires', []) -%}
    - {{req}}
    {% endfor %}

test:
  {#  When we include the tests module in the zipline package, we can use this:
  requires:
    {% for req in data.get('extras_require', {}).get('dev', []) -%}
    - {{req}}
    {% endfor %}
  #}
  # Python imports
  imports:
    - zipline

about:
  home: https://zipline.io
  license: Apache Software License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
